spring.application.name=LB_Calc_Web

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/lb_web_mysql
spring.datasource.username=root
spring.datasource.password=vopreki777
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
#Turn Statistics on
logging.level.org.hibernate.stat= trace
logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss.SSS
