
spring.application.name=LB_Calc_Web

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.type.descriptor.sql=true

logging.level.org.hibernate.stat=trace
logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss.SSS
logging.level.com.lb_calc_web=TRACE

jwt.secret.access=${JWT_SECRET_ACCESS}
jwt.secret.refresh=${JWT_SECRET_REFRESH}
jwt.expiration.access=${JWT_EXPIRATION_ACCESS:36000000}
jwt.expiration.refresh=${JWT_EXPIRATION_REFRESH:252000000}