# ===================================================================
# Параметры валидации размеров компонентов
# Все значения указаны в миллиметрах (мм)
# ===================================================================

# Рамы (верхняя и нижняя)
size.frame.upper.min=20
size.frame.upper.max=300
size.frame.bottom.min=20
size.frame.bottom.max=300


# Высота

#UPPER_FRAME_MIN+BOTTOM_FRAME_MIN+HEIGHT_CELL_MIN
size.height.min=125
size.height.max=2300
size.height.cell.min=85
size.height.lc.min=600
size.height.lc.panel.min=300

# Глубина
size.depth.cell.min=100
size.depth.min=170
size.depth.max=900

size.depth.cell.max=880
# Ширина
size.width.cell.min=100
size.width.max=1200

# Количество ячеек
size.count.cells.min=1
