package notification.event;

public enum UserEventType {

    USER_REGISTERED,
    USER_LOGGED_IN,
    USER_LOGGED_OUT,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED
}